### ISSUE TITLE
如何修改服务器聊天窗语言

### ISSUE THREAD

**Issue by 1790283354** [popstarfreas/Dimensions#104]
例如（英文）
把Shifting to （word name）Dimension
改为（简体中文）
正在传送至（word name）世界

**Comment by popstarfreas** [comment]
If you would be willing to translate the English text, I can add a language option.

Here are the English phrases Dimensions sends to players that I can see:

---

如果您愿意翻译英文文本，我可以添加语言选项。

以下是Dimensions发送给玩家的英文短语，我可以看到：

1.
```
Someone called ${name} is already on the server.
```
2.
```
A character name must be between (inclusive) 2 to 20 characters long.
```
3.
```
Are you even connected?
```
4.
```
You are already in that Dimension.
```
5.
```
Shifting to the ${name} Dimension
```
6
```
You need to wait until you have fully connected to your current Dimension.
```
7
```
There are ${total} players across all Dimensions.
```
8
```
Available Dimensions: 
```
9
```
You have entered the Void. You will soon disappear.
```
10
```
The dimension you were in disconnected you
```
11
```
Reason: 
```

And the commands, if you want them translated as well:
1.
```
/who
```
2.
```
/dimensions
```
3
```
/void
```

**Comment by 1790283354** [comment]
请问语言选项怎么添加，或者它们在那些文件里

**Comment by popstarfreas** [comment]
I will add a new option for you. I just need you to translate the phrases to your language so I can put them in.

--- 

我将为您添加一个新选项。 我只需要你把这些短语翻译成你的语言，这样我就可以把它们放进去。

**Comment by 1790283354** [comment]
1
`${name} 已经进入了服务器`
2
`昵称长度必须在2至20个字符之间`
3
`请确保你已经连接`
4
`你已经进入了那个世界`
5
`正在传送到 ${name}`
6
`请等待传送`
7
`当前共有 ${total} 名玩家在线`
8
`可传送的世界: `
9
`你已断线，即将被踢出世界`
10
`你已与当前世界断开连接`
11
`原因: `
And the commands, if you want them translated as well:
1
`/who`
2
`/世界`
3
`/void`

**Comment by popstarfreas** [comment]
Sorry, I forgot one message:

---

抱歉，我忘记了一条消息：

12
```
Specify a [c/FF00CC:Dimension] to travel to:
```

**Comment by 1790283354** [comment]
12
请选择需要传送的[c/FF00CC:世界]：
13
你所在的世界已与您断开连接

**Comment by popstarfreas** [comment]
It is currently in this branch: https://github.com/popstarfreas/Dimensions/tree/feature/chinese-translation

At some point I will provide a build, unless you are able to run it yourself.

----

目前在这个分支：https://github.com/popstarfreas/Dimensions/tree/feature/chinese-translation

在某些时候我会提供一个构建，除非你能够自己运行它

**Comment by popstarfreas** [comment]
The language option was added in https://github.com/popstarfreas/Dimensions/releases/tag/v6.0.0-beta.0
