### ISSUE TITLE
Player can't see each otcher

### ISSUE THREAD

**Issue by ACaiCat** [popstarfreas/Dimensions#110]
Player can't see each otcher when a player enter a server.If a player is  dead or uses /tp,the other will see the player.

**Comment by popstarfreas** [comment]
Is this without any additional plugins? I tested two non-SSC servers using the latest tshock release and couldn't replicate. What is your setup?

**Comment by ACaiCat** [comment]
My problem is the same as #106

**Comment by ACaiCat** [comment]
Like this
![Screenshot_2022-08-06-23-44-24-33_e263680a0e5220b6eaef081fb22e0255](https://user-images.githubusercontent.com/62058454/183256138-53214a7e-f656-4b27-abe2-1227bb1ac97a.png)
![(RV)0{%TWWTKH)UI1}`IN1Z](https://user-images.githubusercontent.com/62058454/183256143-9165a0f5-a6de-4d5b-b7e5-68acfaaf07d6.png)

**Comment by ACaiCat** [comment]
> Is this without any additional plugins? I tested two non-SSC servers using the latest tshock release and couldn't replicate. What is your setup?


- Two SSC servers 
- No any additional plugins
- TShock 4.5.18
