### ISSUE TITLE
Critical Crash issue, Dividing by Zero (Djinn's Curse).

### ISSUE THREAD

**Issue by tlworks** [popstarfreas/Dimensions#15]
This has been properly tested before hand, is that whenever a person joins (and/or leaves) the Server with the Djinn's Curse equipped (Only on non-SSC Servers) will cause a bunch of random players to Crash (Client crash) due to trying to divide by Zero.

This doesn't happen when using the default port (for example, my main port for the non-SSC Server is 6556) and when joining with a Djinn's curse through there no crash will occur.

**Comment by popstarfreas** [comment]
Fixes for TShock servers available since https://github.com/NyxStudios/TShock/commit/047f9e747510e4dcdb060a72667d1940fdfe16a1 and apparently fixed in 1.3.5
