### ISSUE TITLE
Disable load-balance future?

### ISSUE THREAD

**Issue by tanpro260196** [popstarfreas/Dimensions#26]
Just like the title, I want to disable it. I just want a convenient command for players to move between map, I don't need load-balance.

**Comment by popstarfreas** [comment]
The feature is dependent on if you list two Dimensions under the same Listen Server (port). If you list them separately, there is no load balancing.

[Take this example](https://gist.github.com/popstarfreas/5d4441dc63058a93ba2a9c4e24ea4f7c). Main and Mirror are load balanced, but zombies is listed separately. This means Main/Mirror is not load balanced with zombies.

**Comment by tanpro260196** [comment]
Can players jump from main to zombie if they wanted to?

**Comment by popstarfreas** [comment]
Yes. As long as you block off the zombies port from direct access, then you will be sure they always start at main/mirror, but can then go to zombies or any other Dimension you list. Otherwise you can keep that port open and people can join zombies directly.

**Comment by tanpro260196** [comment]
nice, thank you very much for the assist. :)
