### ISSUE TITLE
Items lost their prefix upon Dimension shifting

### ISSUE THREAD

**Issue by tanpro260196** [popstarfreas/Dimensions#27]
Many players on my server has reported that sometime all their items lost its prefix when they move from one Dimension to another.
This glitch/bug seems to happen randomly and not every users has it.

**Comment by popstarfreas** [comment]
SSC -> Non-SSC, SSC -> SSC?

**Comment by tanpro260196** [comment]
SSC -> SSC, 2 dimension share the same database using mysql.

**Comment by popstarfreas** [comment]
Running Dimensions v4.10.1?

**Comment by tanpro260196** [comment]
Yes.


![capture](https://user-images.githubusercontent.com/12226439/28493941-376a4c94-6ed5-11e7-88bc-0dd25d6fa9d3.PNG)

**Comment by popstarfreas** [comment]
And when you say the prefix is lost, you mean that the item is removed of its prefix, or that it changes to another one?

**Comment by tanpro260196** [comment]
the item is removed of its prefix.

**Comment by tanpro260196** [comment]
ok now I have reports that items' prefix change as well. Warding Golden Chest for example.

**Comment by popstarfreas** [comment]
Do you have only SSC Dimensions, or non-SSC Dimensions too? A quick look sees that a character's inventory is restored on switching from an SSC Dimension, and I've not checked but it looks like it happens regardless of whether they are switching to another SSC Dimension. Now I'm wondering if those prefixes line up with the character's actual inventory because that might suggest something involved with that operation.

How often does this happen?

**Comment by tanpro260196** [comment]
Only SSC Dimensions. It usually happen once every 10-15 dimension-shifting.

**Comment by popstarfreas** [comment]
Is this per person or overall? Is there any consistencies in who has the problem?

**Comment by tanpro260196** [comment]
I never have the problem myself but most players and staffs encountered many times (we have a plugin that check and disable player who have invaild item prefix).
It doesn't seem to target any certain player group or item.  I have seen stuff like Massive Gill Potion or Armored Copper Shortsword. Seem really random to me.

**Comment by popstarfreas** [comment]
But do these prefixes have anything to do with that persons normal (non-SSC, client-side character) inventory?

**Comment by tanpro260196** [comment]
I don't know about that, let's me ask around and see what I can get.

**Comment by tanpro260196** [comment]
Ok, after asking around, here what I got:

1. Seem like it has nothing to do with non-ssc inventory
2. However, the prefix change stay consistent for a perticular item on a perticular player.
Ex: One of my player have a `Space Gun (no prefix)`. Upon dimension shifting, it become `Dull Space Gun` So I gave him a new `Space Gun (no prefix)`. But when he move dimension, it become `Dull Space Gun` again! I repeat that process 3 times and eveytime, the `Space Gun` become `Dull` when he change Dimension.

**Comment by popstarfreas** [comment]
Alright that is helpful. If you can find any way to replicate it that would probably complete this issue. In the meantime I'll just have to poke around to see if I can find any causes.

**Comment by popstarfreas** [comment]
Ok, so before I start properly looking into it, try and see if the removal of inventory restoration when switching between SSC Dimensions changes anything. Also note that you will need to `npm install` to get the new module for reloading that it uses.

https://github.com/popstarfreas/Dimensions/releases/tag/v4.10.2-beta

**Comment by tanpro260196** [comment]
Ok, give me a few days to gather feedback about this.

**Comment by popstarfreas** [comment]
Any updates on the situation?

**Comment by tanpro260196** [comment]
So far nobody has report the problem anymore. Seem to be fixed now.

**Comment by popstarfreas** [comment]
Then this must mean something about the Inventory Restoration process is done incorrectly or at least incorrectly in regards to SSC. I'll mark it as an official release and for now, and I will assume that the restoration works fine when deployed going from SSC to Non-SSC.
