### ISSUE TITLE
[OTAPI] Prefixes being overwritten when moving from SSC to SSC.

### ISSUE THREAD

**Issue by tlworks** [popstarfreas/Dimensions#3]
As noted in the title, whenever you log onto a SSC Server and switch to another SSC server, the prefix you currently have on the item you are holding will transfer over to the other SSC Server. Allowing the user to obtain prefixes on items normally not possible.

Though TShock should automatically get rid of wrong prefixes, this isn't always the case.

**Comment by popstarfreas** [comment]
Fixed from https://github.com/popstarfreas/Dimensions/commit/12fcb85c72147b72783fc7b60cad28d77e4558ab
