### ISSUE TITLE
About ip ban will ban 127.0.0.1

### ISSUE THREAD

**Issue by AxeelAnder** [popstarfreas/Dimensions#36]
if banned a person when ip ban is enable, it will ban 127.0.0.1. It causes all players banned. Disable it will be inconvenient. Is it possible to record real ip of players?

**Comment by mistzzt** [comment]
Follow step 3 mentioned in the README file.

**Comment by popstarfreas** [comment]
If you ban someone using tshock's ban command, it should ban their real ip if you have the Dimensions plugin (https://bitbucket.org/popstarfreas/dimensions-plugin/downloads/).

**Comment by AxeelAnder** [comment]
Oh, thanks, I installed the plugin on my computer but forgot it when installing on the server😭
