### ISSUE TITLE
[OTAPI] Health not properly moving over from SSC to NSSC.

### ISSUE THREAD

**Issue by tlworks** [popstarfreas/Dimensions#4]
As noted in the title above, when switching from a SSC Server to NSSC Server, the current health will be overwritten in the current session, though this isn't a big issue unless the server contains of health modifications which could be abused.

(Not tested with a character containing 100 health > joining SSC and obtaining 500 health & leaving and check if the user still has 500 health in the Menu).

**Comment by popstarfreas** [comment]
Fixed from https://github.com/popstarfreas/Dimensions/commit/12fcb85c72147b72783fc7b60cad28d77e4558ab
