### ISSUE TITLE
[OTAPI] SSC Inventories overwriting Singleplayer (NSSC) Inventories.

### ISSUE THREAD

**Issue by tlworks** [popstarfreas/Dimensions#5]
As noted in the title above, whenever a user moves from an SSC Server to an NSSC Server throughout the use of the dimension switch command, the singleplayer inventory will be overwritten by the SSC one. This is not the case when leaving the SSC Server through the Exit option and joining again.

This does not happen vice-versa.

**Comment by popstarfreas** [comment]
Fixed from https://github.com/popstarfreas/Dimensions/commit/12fcb85c72147b72783fc7b60cad28d77e4558ab
