### ISSUE TITLE
World Size Overlaps

### ISSUE THREAD

**Issue by Moneylover3246** [popstarfreas/Dimensions#63]
World Sizes overlap upon switching Dimensions (ex. switching from a small world to a large world will keep the small world canvas, and vice versa.)

**Comment by popstarfreas** [comment]
Not sure what you mean

**Comment by Moneylover3246** [comment]
Basically when worlds are different sizes, Dimensions will tend to keep the same size of the first world you joined.

Example, World 1 is Small, World 2 is Medium, World 3 is large.

You originally join on World 2 (Basically the 7777 port in this case). If you switch to a large world, dimensions will still think you're in a medium world, and the extra chunks in the large world won't be there.

If you switch to a small world, the world will give you extra chunks, and you'll be able to go past the ocean border, where you'll eventually crash.

I don't believe that the Medium -> Small World scenario will give extra space on the Y-Axis, however it will give extra chunks on the X.

**Comment by popstarfreas** [comment]
This is a game limitation, nothing Dimensions can do about it.
