### ISSUE TITLE
IP banning a player will ban 127.0.0.1

### ISSUE THREAD

**Issue by Moneylover3246** [popstarfreas/Dimensions#66]
I've seen a closed issue about the same problem. However even though I have Dimensions.dll installed, the problem won't fix

**Comment by EMREOYUN** [comment]
> I've seen a closed issue about the same problem. However even though I have Dimensions.dll installed, the problem won't fix

I don't know what that causes but i fixed by building a custom version of Dimensions to fix this issue. It worked but i don't know how.

**Comment by Moneylover3246** [comment]
Not working for me

**Comment by EMREOYUN** [comment]
> Not working for me

Consider building the code yourself i think
