### ISSUE TITLE
is there an event for playerdeath? I'm trying to make a dimensions extension

### ISSUE THREAD

**Issue by Moneylover3246** [popstarfreas/Dimensions#67]
^

**Comment by popstarfreas** [comment]
https://github.com/popstarfreas/Dimensions/blob/dev/app/node_modules/dimensions/extension/index.ts
That's essentially all the hooks there are. If you want to handle player death, you could just add a handler for the packet itself either from the client or server (not sure if the server sends the packet to the client to kill it, if the client sends it back or not).

**Comment by Moneylover3246** [comment]
also I'm getting this error when I'm testing my extension

TypeError: utils_1.requireNoCache(...).default is not a constructor
    at C:\Users\A\Downloads\Dimensions-1.4\build\node_modules\dimensions\extensions.js:10:35
    at Array.forEach (<anonymous>)
    at Function.loadExtensions (C:\Users\A\Downloads\Dimensions-1.4\build\node_modules\dimensions\extensions.js:9:53)
    at new Dimensions (C:\Users\A\Downloads\Dimensions-1.4\build\node_modules\dimensions\index.js:32:30)
    at Object.<anonymous> (C:\Users\A\Downloads\Dimensions-1.4\build\index.js:15:18)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)

is there a fix for this?

**Comment by popstarfreas** [comment]
That would point to whatever you extensions's index.js/index.ts file is doesn't export a class properly (or at all). This is an example of a plugin: https://github.com/popstarfreas/Dimensions-PlayerInfo/blob/master/app/index.ts

**Comment by Moneylover3246** [comment]
I can't really see the issue: 

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const configloader_1 = require("./configloader");
const utils_1 = require("dimensions/utils");
let client;
let gameStarted = false;
class PvEHandler {
    constructor() {
        this.name = "PvEHandler";
        this.version = "v1.0";
        this.author = "Moneylover3246";
        this.config = configloader_1.Config;
        this.reloadable = true;
    }
    reload(require) {
        this.config = utils_1.requireNoCache('./extensions/PvE/config.js', require);
    }
    serverDisconnectPreHandler(server) {
        // code
        }
        return handled;
    }
     
}
exports.default =  PvEHandler;
//# sourceMappingURL=index.js.map

Can you pinpoint what's wrong with this?

**Comment by popstarfreas** [comment]
Looks fine to me. Make sure it's complaining about the right file:
https://github.com/popstarfreas/Dimensions/blob/dev/app/node_modules/dimensions/extensions.ts#L16
Before that line you can add:
```
console.log(path.resolve(file))
```
And it should print out what file it is trying to load an extension from. It's possible you have another index.js somewhere it is trying to load from

**Comment by Moneylover3246** [comment]
So I found the other place where the extension was trying to load from. How can I modify the code so it doesn't do that?

**Comment by Moneylover3246** [comment]
If it's important I found the file inside a node modupe via my extension

**Comment by Moneylover3246** [comment]
Nevermind I just had to remove the folder T_T

**Comment by Moneylover3246** [comment]
So I realized that because I set the handled bool to be false, the dimensions switch won't happen unless I retype the command again. Is there a way to handle the command from the function I'm creating, or to wait until the dimensions switch has occurred to start my code? 

Example: I want to go to a world called lobby,  I use the command /lobby to go to the world, it won't take me there so I retype the command to actually take me to said world.

**Comment by Moneylover3246** [comment]
Ok so I realized that because my method name was "serverDisconnectPreHandler", that handles when the player disconnects from the server. I would like to know what all of these handler names are, mainly for a player joining.

**Comment by popstarfreas** [comment]
Don't know what you mean about dimensions switch not happening.

https://github.com/popstarfreas/Dimensions/blob/dev/app/node_modules/dimensions/extension/index.ts
That file contains the definition of extensions. Look at where it says "severDisconnectPreHandler" there's a list of them around there. `clientFullyConnectedHandler` is called when a player finishes connecting to a dimension.

**Comment by Moneylover3246** [comment]
alright. I'll check it out

**Comment by Moneylover3246** [comment]
and does SendChatMessage have an option to broadcast to All, or do I run a foreach loop through each client in the server?

**Comment by popstarfreas** [comment]
It doesn't. You will need to go through each client and send it that way, yes.

**Comment by Moneylover3246** [comment]
I'm also aware that for your Zombies map, you have certain dimensions that aren't visible in the client.servers table. How did you manage to hide it?

**Comment by popstarfreas** [comment]
Servers can send a dimension packet with an given ip and port to get the client to be connected to anything. So, our zombies setup spawns processes that bind on an unbound port and then that port gets passed to dimensions.  These are called dynamic dimensions because they aren't defined in the config.

https://github.com/popstarfreas/Dimensions/blob/1499913ec99796008467ce0030c7a068be391820/app/node_modules/dimensions/terrariaserverpackethandler.ts#L387
That's where in the code the packet is read and the switch is started.

**Comment by EMREOYUN** [comment]
> So I realized that because I set the handled bool to be false, the dimensions switch won't happen unless I retype the command again. Is there a way to handle the command from the function I'm creating, or to wait until the dimensions switch has occurred to start my code?
> 
> Example: I want to go to a world called lobby, I use the command /lobby to go to the world, it won't take me there so I retype the command to actually take me to said world.

I have a similar issue but we need type //lobby for entering the lobby. I fixed it by fixing changing the entire chat handler to port Mobile clients can use it.

**Comment by EMREOYUN** [comment]
If you using Mobile Version of Terraria, you need use handleChatMessage instead of handleLoadNetModule. In Mobile clients, handleLoadNetModule not used in chat messages.

**Comment by Moneylover3246** [comment]
This question has absolutely nothing to do with this question, but how can I learn how to rerun OTAPI, because I was working on plugins upon the release of 1.4.1, and I have absolutely no idea how to get OTAPI patched. If you could help thanks in advance

**Comment by Moneylover3246** [comment]
I'm also trying to setup MCL for 1.4, however when I try to join from mobile, I get kicked for having a blank name, what's the deal with that?

**Comment by popstarfreas** [comment]
The discussion for this issue seems to have come to a halt. Avoiding adding noise to it and post queries in their relevant locations.
