### ISSUE TITLE
SSC

### ISSUE THREAD

**Issue by Moneylover3246** [popstarfreas/Dimensions#68]
When I join an SSC server via dimensions, then leave said server, my inventory gets purged. Is there a fix for this?

**Comment by popstarfreas** [comment]
What inventory?

**Comment by Moneylover3246** [comment]
My player inventory

**Comment by Moneylover3246** [comment]
Non SSC

**Comment by Moneylover3246** [comment]
Dinensions problem

**Comment by EMREOYUN** [comment]
Dimensions does not support SSC i think. I never tried with them.

**Comment by tlworks** [comment]
> Dimensions does not support SSC i think. I never tried with them.

:WeirdChamp: Dimensions does support SSC, what have you been smoking?

**Comment by EMREOYUN** [comment]
> > Dimensions does not support SSC i think. I never tried with them.
> 
> :WeirdChamp: Dimensions does support SSC, what have you been smoking?

First of all, explain why his character got reset?
Second, I NEVER TRIED THEM and i wrote it there if youbcan read.
