### ISSUE TITLE
Latest Dev Build Fails Start

### ISSUE THREAD

**Issue by TheBambino** [popstarfreas/Dimensions#73]
npm: '6.14.10'
os: windows 10

![image](https://user-images.githubusercontent.com/9632779/106686726-77878c00-6590-11eb-909b-f4e3a5d6c8a5.png)

[2021-02-03T01_52_52_953Z-debug.log](https://github.com/popstarfreas/Dimensions/files/5915564/2021-02-03T01_52_52_953Z-debug.log)

**Comment by popstarfreas** [comment]
Did you build it?
Try using `npm run bstart` instead which builds then starts it.

**Comment by PhoenixGTX** [comment]
Hi everyone! Have same issue on my windows 10 VM in proxmox , nmp 6.14.10. When i tryed `npm run bstart`:
![image](https://user-images.githubusercontent.com/78582714/106995474-0adae000-6790-11eb-8947-1406be6ab180.png)

**Comment by PhoenixGTX** [comment]
![image](https://user-images.githubusercontent.com/78582714/107003230-7d9e8800-679d-11eb-9c90-5aa7304d8fc3.png)

“command is not recognized as an internal or external command, operable program or batch file”

**Comment by popstarfreas** [comment]
Have you run `npm install` yet?

**Comment by PhoenixGTX** [comment]
Yep, like in your manual. `npm install --only=production`

**Comment by TheBambino** [comment]
I did exactly as instructed and have used previous versions. I got it working by using `npm install`, `npm run-script build`, manually creating the log folder, renaming the config file, then `npm run start`.

**Comment by popstarfreas** [comment]
> Yep, like in your manual. `npm install --only=production`

That's only for production, not dev. Look at the other section.

**Comment by PhoenixGTX** [comment]
I think i am stupid ). Dimensions-master.zip this one for use?

**Comment by PhoenixGTX** [comment]
![image](https://user-images.githubusercontent.com/78582714/107019689-07a51b80-67b3-11eb-818a-686f5a7e4eed.png)


> I did exactly as instructed and have used previous versions. I got it working by using `npm install`, `npm run-script build`, manually creating the log folder, renaming the config file, then `npm run start`.

Yeah its realy work.

**Comment by PhoenixGTX** [comment]
Thank you!
