### ISSUE TITLE
If  you ban someone it bans 127.0.0.1?

### ISSUE THREAD

**Issue by OzzTerraria** [popstarfreas/Dimensions#85]
I'm not sure where to post this, but I think it should be posted here, but whenever someone registered on my dimensions server, It doesn't show their real IP, I can only see a localhost (127.0.0.1) as their IP, Which makes banning players even harder as banning someone will ban the Localhost, banning every player in the process.

**Comment by popstarfreas** [comment]
That usually means the dimensions plugin you are using is not compatible with the server (likely tshock) version.
