### ISSUE TITLE
How to use Crossplay in Dimensions  properly？

### ISSUE THREAD

**Issue by wujiawei131108** [popstarfreas/Dimensions#94]
Crossplay work in routing servers normally,but not work in other server.How to deal it or  modify the code to make Crossplay work normally.

**Comment by popstarfreas** [comment]
Can you explain more about your setup?
Currently, the official way (at Dark Gaming) is that we use [1421 -> 1411](https://github.com/popstarfreas/dimensions-mcl/tree/feature/1421) and [1405 -> 1411](https://github.com/popstarfreas/dimensions-mcl/tree/feature/mobile-1.4) on Terraria Server versions v1.4.1.1 and lower.

**Comment by wujiawei131108** [comment]
OK，I will try.Thanks
