### ISSUE TITLE
Considering reading config file path from environment variable

### ISSUE THREAD

**Issue by hyf3513OneGO** [popstarfreas/Dimensions#96]
During dockerize this load balancer，I found that if this application can provide an implement to read config path from environmental variable，with redis reload method，its config reading can be much flexible

I wanna add few codes in ‘configloader.js’ to fulfil this feature  like bellow
![image](https://user-images.githubusercontent.com/67197231/163566161-f3e774a9-6fbb-45c4-91f8-45cd5610ba8e.png)

Is it a proper way to implement it like this？

**Comment by popstarfreas** [comment]
You don't want to use a bind mount? Are you expecting to put an entire config file into an environment variable?

**Comment by popstarfreas** [comment]
Also `process.env.DIMENSIONS_CONFIG` would be a string, whereas it is expecting an object. So at the very least you would want to use `JSON.parse(process.env.DIMENSIONS_CONFIG)` to turn the string into an object, assuming your string is valid json.

**Comment by hyf3513OneGO** [comment]
THX，this is really helpful
